---
apiVersion: v2
description: A chart to power Immich (immich.app) running on kubernetes
name: immich
version: 0.0.1
maintainers:
  - name: PixelJonas
    email: 5434875+PixelJonas@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.1.0
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Automatically set `global.nameOverride` to release name
